name: fingerprint2.0 CD

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
  deployment:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: |
          npm i
          CI=false npm run build
          sudo service nginx restart
